version: '3'

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - secret.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    external: true
