version: "3.3"

x-volumes:
  shoko-config: &shoko-config /media/Media/Shoko:/home/shoko/.shoko
  import-path: &import-path /home/kvineet/Downloads/torrents:/data/import
  content: &content /srv/webDav:/data/content

services:
  shoko:
    image: docker.io/shokoanime/server:latest
    labels:
      - in.kvineet.pc1.shoko.service=shoko
    container_name: shoko
    restart: unless-stopped
    working_dir: /home/shoko/
    env_file:
      - ../common.env
      - ./common.env
    expose:
      - 8111/tcp
    volumes:
      - *shoko-config
      - *import-path
      - *content
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    external: true
