version: "3.3"

services:
  base:
    restart: unless-stopped
    env_file:
    - ../common.env
    - ./common.env
    networks:
    - traefik
networks:
  traefik:
      name: traefik
      external: true