version: "3.3"

services:
  flood:
    extends:
      file: base.yml
      service: base
    image: jesec/flood
    labels:
      - in.kvineet.pc1.torrent.service=flood
    container_name: flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /webdav
    environment:
      HOME: /root
    expose: 
      - 3001/tcp
    ports:
      - target: 3001
        published: 13372
        protocol: tcp
        mode: host
  rtorrent:
    extends:
      file: base.yml
      service: base
    image: jesec/rtorrent
    labels:
      - in.kvineet.pc1.torrent.service=rtorrent
    container_name: rtorrent
    user: 1000:1001
    restart: unless-stopped
    command: -o network.port_range.set=6881-6881,system.daemon.set=true
    environment:
      HOME: /root
    expose: 
      - 6881/tcp
    ports:
      - target: 6881
        published: 52264
        protocol: tcp
        mode: host