version: "3.3"

services:
  sonarr:
    extends:
      file: base.yml
      service: base
    image: lscr.io/linuxserver/sonarr:latest
    labels:
      - in.kvineet.pc1.torrent.service=sonarr
    container_name: sonarr
    environment:
      - SONARR_BRANCH=main
    expose:
      - 8989/tcp