version: "3.3"

services:
  sonarr:
    extends:
      file: base.yml
      service: base
    image: lscr.io/linuxserver/sonarr:latest
    labels:
      - in.kvineet.pc1.torrent.service=sonarr
      # - 'traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`)'
      - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
      - 'traefik.http.routers.whoami.rule=PathPrefix(`/sonarr{regex:$$|/.*}`)'
    container_name: sonarr
    environment:
      - SONARR_BRANCH=main
    expose:
      - 8989/tcp