version: "3.3"

x-volumes:
  jellyfin-config: &jellyfin-config /media/Media/Jellyfin:/config
  webdav: &webdav /srv/webDav:/data/content

services:
  jellyfin-server:
    image: docker.io/linuxserver/jellyfin:latest
    labels:
      - in.kvineet.pc1.torrent.service=jellyfin
    container_name: jellyfin-server
    restart: unless-stopped
    env_file:
    - ../common.env
    - ./common.env
    environment:
      - HOME=/tmp
      - AMDGPU_IDS=/share/libdrm/amdgpu.ids
      - FONTCONFIG_PATH=/etc/fonts
      - LD_LIBRARY_PATH=/lib:/system
      - LIBVA_DRIVERS_PATH=/lib/dri
      - OCL_ICD_VENDORS=/etc/OpenCL/vendors
      - PCI_IDS_PATH=/share/hwdata/pci.ids
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - target: 8096
        published: 13385
        protocol: TCP
        mode: host
      - target: 7359
        published: 7359
        protocol: UDP
        mode: host
      - target: 1900
        published: 1900
        protocol: UDP
        mode: host
    volumes:
      - *jellyfin-config
      - *webdav
networks:
  default:
      name: jellyfin
      external: true