version: "3.3"

x-volumes:
  jellyfin-config: &jellyfin-config /media/Media/Jellyfin:/config
  webdav: &webdav /srv/webDav:/data/content

services:
  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    labels:
      - in.kvineet.pc1.torrent.service=jellyfin
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.localhost`)'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
    container_name: jellyfin
    restart: unless-stopped
    env_file:
    - ../common.env
    - ./common.env
    environment:
      - HOME=/tmp
      - AMDGPU_IDS=/share/libdrm/amdgpu.ids
      - FONTCONFIG_PATH=/etc/fonts
      - LD_LIBRARY_PATH=/lib:/system
      - LIBVA_DRIVERS_PATH=/lib/dri
      - OCL_ICD_VENDORS=/etc/OpenCL/vendors
      - PCI_IDS_PATH=/share/hwdata/pci.ids
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    expose:
      - 8096/tcp
      - 7359/udp
      - 1900/udp
    volumes:
      - *jellyfin-config
      - *webdav
    networks:
      - traefik
networks:
  traefik:
      name: traefik
      external: true