version: "2.1"

x-volumes:
  youtubedl-config: &youtubedl-config ./conf:/config
  webdav: &webdav /media/Media/Youtubedl/:/downloads

services:
  youtubedl:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl
    env_file:
      - ../common.env
      - ./common.env
    environment:
      - youtubedl_webui=true
    ports:
      - "13386:8080"
    volumes:
      - *youtubedl-config
      - *webdav
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    external: true
